# Taps
tap 'homebrew/bundle'
tap 'nicoverbruggen/homebrew-cask'

# Binaries
brew 'ack'
brew 'agent-browser'
brew 'bash' # Latest Bash version
brew 'coreutils' # Those that come with macOS are outdated
brew 'composer'
brew 'doctl' # Digital Ocean
brew 'ffmpeg'
brew 'gh'
brew 'git'
brew 'glab'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'libmemcached'
brew 'mackup'
brew 'memcached'
brew 'ncdu'
brew 'php' # needed by herd compiling php extensions
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'podman'
brew 'podman-compose'
brew 'trash' # Manage the Trash bin
brew 'tree' # List directories in a tree structure
brew 'yarn'
brew 'yt-dlp'
brew 'wget'
brew 'wp-cli'
brew 'zlib' # Needed for Memcached

# Zsh
brew 'zsh-autosuggestions'

## Modern CLI Tools
brew 'bat'
brew 'eza'
brew 'ripgrep'
brew 'fd'
brew 'git-delta'
brew 'fzf'
brew 'jq'
brew 'yq'

# Development tools
cask 'claude-code'

# Apps
cask '1password'
cask '1password-cli'
cask 'bitwarden'
cask 'brave-browser'
cask 'chatgpt'
cask 'claude'
cask 'codex'
cask 'discord'
cask 'podman-desktop'
cask 'dropbox'
cask 'figma'
cask 'github'
cask 'google-chrome'
cask 'herd'
cask 'hyper'
cask 'imageoptim'
cask 'nextcloud'
cask 'phpstorm'
cask 'raycast'
cask 'signal'
cask 'slack'
cask 'spotify'
cask 'the-unarchiver'
cask 'visual-studio-code'
cask 'zoom'

# Quicklook
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'betterzip'
cask 'suspicious-package'

# Fonts
cask 'font-lato'
cask 'font-open-sans'
cask 'font-roboto'
cask 'font-source-code-pro-for-powerline'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
